#! /bin/sh

# usage: ./copy_structure user pwd sourcedb destdb

mysql -u $1 -p$2 -e "drop database $4"
mysql -u $1 -p$2 -e "create database $4 character set utf8 collate utf8_unicode_ci"
mysqldump -u $1 -p$2 -d $3 | mysql -u $1 -p$2 -D $4
